Add FreeBSD implementations for srn_get_executable_{path,dir}
SrainApp/srain pull request #269
Opened 2020-10-02 22:04 UTC by wahjava

This PR provides the implementations of `srn_get_executable_path()` and `srn_get_executable_dir()` functions. This implementation should also work on other BSD OSs too, but I didn't get to test it.

You can read more about it in FreeBSD's [sysctl(3)](https://www.freebsd.org/cgi/man.cgi?query=sysctl&sektion=3&manpath=FreeBSD+12.1-RELEASE&arch=default&format=html) manpage.

Thanks!

2020-10-03 13:06 UTC, SilverRainZ requested changes

2020-10-03 13:06 UTC, SilverRainZ commented on src/lib/path.c
> +    return g_build_filename(realPath, NULL);
Just use `g_strdup`?

2020-10-03 13:06 UTC, SilverRainZ commented on src/lib/path.c
> +    size_t sz = sizeof( rawPath );
Can you please remove the whitespace between brackets？

2020-10-10 05:38 UTC, wahjava commented
Thank you for the review. I've incorporated the requested changes in 5715fe2.

2020-10-11 12:17 UTC, merged